{{- if .Values.Kubernetes -}}
{{- if .Values.fluentd.enable -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: fluentd
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  matchRegex: (?:kube|service)\.(.*)
  forward:
    host: {{ .Values.fluentd.name }}.{{ .Release.Namespace }}.svc
    port: {{ .Values.fluentd.forward.port }}
{{- end }}
{{- end }}