{{- if .Values.Kubernetes -}}
{{- if .Values.fluentbit.output.kafka.enable -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: kafka
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  matchRegex: (?:kube|service)\.(.*)
  kafka:
    brokers: {{ .Values.fluentbit.output.kafka.brokers }}
    topics: {{ .Values.fluentbit.output.kafka.topics }}
{{- end }}
{{- end }}